services:
  - type: web
    name: micmonitor-server
    runtime: node
    region: singapore
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: STUN_URL
        value: stun:stun.l.google.com:19302
